@echo off
rem ========================================================================
rem  Virtual Whip - standalone installer (single file, no prerequisite)
rem
rem  Contains the extension (.vsix, native overlay already compiled) and installs it
rem  into VS Code, VS Code Insiders and/or VSCodium, whichever are present.
rem
rem    install-virtual-whip.bat              installs (or updates) the extension
rem    install-virtual-whip.bat uninstall    uninstalls it
rem    install-virtual-whip.bat /s           silent mode (no pause at the end)
rem
rem  Requirements: Windows 10/11 (.NET Framework 4 is there by default) and VS Code 1.93+.
rem  Advanced: the WHIP_CODE_ARGS variable adds arguments to the "code" command
rem  (for example --extensions-dir "D:\my-extensions").
rem
rem  This file is generated by "npm run installer": do not edit it by hand, the payload
rem  (the ::B64: lines) is the .vsix encoded in base64.
rem ========================================================================
setlocal EnableExtensions

set "EXT_ID=local.virtual-whip"
set "VERSION=@@VERSION@@"
set "SELF=%~f0"
rem Capture before the argument loop: "shift" also shifts %0.
set "SELF_DIR=%~dp0"
set "VSIX=%TEMP%\virtual-whip-%VERSION%.vsix"
set "MODE=install"
set "SILENT="
set /a FOUND=0
set /a FAILED=0

:args
if "%~1"=="" goto :args_done
if /i "%~1"=="uninstall" set "MODE=uninstall"
if /i "%~1"=="/s" set "SILENT=1"
shift
goto :args
:args_done

echo.
echo ==========================================
echo   Virtual Whip %VERSION%
echo ==========================================
echo.

if /i "%MODE%"=="uninstall" goto :find_editors

rem --- .NET Framework 4 (present by default on Windows 10 and 11)
if exist "%WINDIR%\Microsoft.NET\Framework\v4.0.30319\clr.dll" goto :extract
echo [WARNING] .NET Framework 4 was not found: the overlay will not be able to start.
echo           Install it through Windows Update, then run this script again.
echo.

:extract
echo Extracting the extension...
powershell -NoProfile -ExecutionPolicy Bypass -Command "$b = (Get-Content -LiteralPath $env:SELF | Where-Object { $_.StartsWith('::B64:') } | ForEach-Object { $_.Substring(6).Trim() }) -join ''; [IO.File]::WriteAllBytes($env:VSIX, [Convert]::FromBase64String($b))"
if errorlevel 1 goto :extract_failed
if not exist "%VSIX%" goto :extract_failed

:find_editors
call :try_editor "Visual Studio Code" code "%LOCALAPPDATA%\Programs\Microsoft VS Code\bin\code.cmd" "%ProgramFiles%\Microsoft VS Code\bin\code.cmd"
call :try_editor "VS Code Insiders" code-insiders "%LOCALAPPDATA%\Programs\Microsoft VS Code Insiders\bin\code-insiders.cmd" "%ProgramFiles%\Microsoft VS Code Insiders\bin\code-insiders.cmd"
call :try_editor "VSCodium" codium "%LOCALAPPDATA%\Programs\VSCodium\bin\codium.cmd" "%ProgramFiles%\VSCodium\bin\codium.cmd"

if %FOUND%==0 goto :no_editor
if %FAILED% GTR 0 goto :failed
if /i "%MODE%"=="uninstall" goto :uninstalled

echo.
echo ==========================================
echo   Installation complete
echo ==========================================
echo.
echo Restart VS Code (or Ctrl+Shift+P then "Developer: Reload Window").
echo.
echo Getting started:
echo   1. Click "Whip off" in the status bar, or press Ctrl+Alt+F, to show the whip.
echo   2. Start Claude Code in a VS Code terminal (or open the Copilot chat and click
echo      once in its input box), then flick the mouse sharply to crack the whip.
echo   Settings: Ctrl+, then search for "virtualWhip".
echo   Uninstall: install-virtual-whip.bat uninstall
set "RC=0"
goto :finish

:uninstalled
echo.
echo Extension uninstalled. Restart VS Code.
set "RC=0"
goto :finish

:no_editor
echo.
echo [ERROR] No installation of VS Code, VS Code Insiders or VSCodium was found.
echo         Install VS Code (https://code.visualstudio.com), leaving "Add to PATH"
echo         checked, then run this script again.
if /i "%MODE%"=="uninstall" goto :no_editor_end
if not exist "%VSIX%" goto :no_editor_end
copy /y "%VSIX%" "%SELF_DIR%virtual-whip-%VERSION%.vsix" >nul
echo.
echo Manual installation is possible: the file virtual-whip-%VERSION%.vsix was
echo placed next to this script. In VS Code: Extensions, "..." menu, then
echo "Install from VSIX...".
:no_editor_end
set "RC=1"
goto :finish

:failed
echo.
echo [ERROR] The operation failed in at least one editor (see above).
echo         Check that VS Code is up to date (version 1.93 minimum) and close any
echo         installation dialog that is still open, then try again.
set "RC=1"
goto :finish

:extract_failed
echo.
echo [ERROR] Unable to extract the extension from this file. It may be incomplete:
echo         copy it again in full (it should be larger than 50 KB).
set "RC=1"
goto :finish

:finish
if exist "%VSIX%" del /q "%VSIX%" >nul 2>&1
echo.
if not defined SILENT pause
endlocal & exit /b %RC%

rem ------------------------------------------------------------------------
rem  :try_editor <label> <command> <path1> <path2>
rem ------------------------------------------------------------------------
:try_editor
set "CMD_PATH="
rem The full path is required: called without one, the "code" command (code.cmd) computes
rem its own folder (%~dp0) wrongly and can no longer find Code.exe.
for /f "delims=" %%I in ('where %~2 2^>nul') do call :pick_cmd "%%~I"
if not defined CMD_PATH if exist "%~3" set "CMD_PATH=%~3"
if not defined CMD_PATH if exist "%~4" set "CMD_PATH=%~4"
if not defined CMD_PATH exit /b 0
set /a FOUND+=1
call :process "%~1" "%CMD_PATH%"
exit /b 0

:pick_cmd
if defined CMD_PATH exit /b 0
if /i "%~x1"==".cmd" set "CMD_PATH=%~1"
if /i "%~x1"==".exe" set "CMD_PATH=%~1"
if /i "%~x1"==".bat" set "CMD_PATH=%~1"
exit /b 0

:process
echo --- %~1
if /i "%MODE%"=="uninstall" goto :do_uninstall
call "%~2" %WHIP_CODE_ARGS% --install-extension "%VSIX%" --force
if errorlevel 1 goto :process_failed
echo [OK] Extension installed in %~1.
exit /b 0
:do_uninstall
call "%~2" %WHIP_CODE_ARGS% --uninstall-extension %EXT_ID%
exit /b 0
:process_failed
echo [ERROR] The installation in %~1 failed.
set /a FAILED+=1
exit /b 0
